CREATE TABLE `router1_rt_flow` (
  `datetime` datetime DEFAULT NULL,
  `action` varchar(7) DEFAULT NULL,
  `reason` varchar(20) DEFAULT NULL,
  `src_ip` varchar(39) DEFAULT NULL,
  `src_port` smallint(5) unsigned DEFAULT NULL,
  `dst_ip` varchar(39) DEFAULT NULL,
  `dst_port` smallint(5) unsigned DEFAULT NULL,
  `src_ip_nat` varchar(39) DEFAULT NULL,
  `src_port_nat` smallint(5) unsigned DEFAULT NULL,
  `dst_ip_nat` varchar(39) DEFAULT NULL,
  `dst_port_nat` smallint(5) unsigned DEFAULT NULL,
  `service` varchar(50) DEFAULT NULL,
  `src_nat_rule` varchar(50) DEFAULT NULL,
  `dst_nat_rule` varchar(50) DEFAULT NULL,
  `protocol` tinyint(3) unsigned DEFAULT NULL,
  `policy` varchar(50) DEFAULT NULL,
  `src_zone` varchar(50) DEFAULT NULL,
  `dst_zone` varchar(50) DEFAULT NULL,
  `application` varchar(50) DEFAULT NULL,
  `nested_app` varchar(50) DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  `role` varchar(50) DEFAULT NULL,
  `session_id` int(10) unsigned DEFAULT NULL,
  `src_int` varchar(20) DEFAULT NULL,
  `pkts` int(10) unsigned DEFAULT NULL,
  `bytes` int(10) unsigned DEFAULT NULL,
  `session_time` int(10) unsigned DEFAULT NULL,
  `seq` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`seq`),
  KEY `datetime` (`datetime`)
) ENGINE=InnoDB;